### ISSUE TITLE
A question about the number of triplets in new training data

### ISSUE THREAD

**Issue by ghost** [pouyapez/criage#1]
It 's an interesting work!
    But I wonder if it is appropriate to inject all the attack examples in new training data at once. For example, we generate one attack example for a test triplet, and we will inject 1*N attack examples into new training data(the number of triplets in test data is N in total). 
    I think this operation would enlarge the effect of the attack.
    Thanks~~~

**Comment by YifanTian** [comment]
Hi, we observed that if we inject several attack examples. Then the influence function still works. But the accuracy will decrease compared with only injecting one example.

**Comment by ghost** [comment]
Thanks for your reply. I observed that all the attack examples are injected in data/new_WN-18/train.txt. And the polluted embeddings are learned on this file. I think it may be not appropriate.
Is it that I have misunderstood?
