### ISSUE TITLE
AttributeError: 'Vocab' object has no attribute 'tokendicts'

### ISSUE THREAD

**Issue by ghost** [pouyapez/criage#2]
I met this error when I run main.py. And in the corresponding package(https://github.com/TimDettmers/spodernet/spodernet/preprocessing/vocab.py), I find that there is no attribute 'tokendicts'.  

Thanks~

**Comment by Kevin99z** [comment]
I met the same problem, have you solved it @MGwave?

**Comment by NinaCalvi** [comment]
did you resolve this?
